### ISSUE TITLE
Крашит.

### ISSUE THREAD

**Issue by Avocen** [Vecz/vk_bot#1]
File "main.py", line 286
SyntaxError: Non-UTF-8 code starting with '\xd0' in file main.py on line 286, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by Vecz** [comment]
Вероятнее всего нет папки png(она нужна для сохранения статистики).

**Comment by Vecz** [comment]
Добавил в код автоматическое создание папок.

**Comment by Avocen** [comment]
Неа,проблема не ушла
Проблему решил добавлением кодировки на 1 строке
т.е перед кодом надо прописать "# -*- coding: utf8 -*-"
